# Generated by Django 3.2 on 2021-04-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('reviewtext', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField()),
                ('snack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacks.snack')),
            ],
        ),
        migrations.AddField(
            model_name='snack',
            name='tags',
            field=models.ManyToManyField(to='snacks.Tag'),
        ),
    ]
