# Generated by Django 3.2 on 2021-05-04 14:09

from django.db import migrations, models
import django.db.models.deletion
import snacks.models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to=snacks.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='snack_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snacks.snack'),
        ),
    ]
